export default {
    commerceList: [
      {
        id: 1,
        tipo: 'Restaurante',
        name: 'Portal Sul Costelaria',
        rating: 4,
        distance: '3km de distância',
        checkins: 2,
        favorite: true,
        Rua: 'Estr. Prof. Cândido Mota Filho, 195',
        Bairro: ' Jardim Recanto da Fonte',
        Municipio: 'Embu das Artes',
        Estado: 'São Paulo',
        CEP: '06804-445',
        latitude:  -33.64702,
        longitude: -56.84903
      },
      // {
      //   id: 2,
      //   name: 'Centro Histórico de Embu das Artes',
      //   tipo: 'Atrações',
      //   rating: 3,
      //   distance: '5km de distância',
      //   checkins: 5,
      //   favorite: false,
      //   Rua: 'Largo 21 de Abril, 29',
      //   Bairro: ' Centro',
      //   Municipio: 'Embu das Artes',
      //   Estado: 'São Paulo',
      //   CEP: '06803-400',
      //   latitude:  -20.64702,
      //   longitude: -40.84903
      // },
      // {
      //   id: 3,
      //   name: 'Kenzu',
      //   tipo: 'Restaurante',
      //   rating: 5,
      //   distance: '5km de distância',
      //   checkins: 5,
      //   favorite: true,
      //   Rua: 'R. Paulo do Vale, 221',
      //   Bairro: 'Centro',
      //   Municipio: 'Embu das Artes',
      //   Estado: 'São Paulo',
      //   CEP: '06804-040',
      //   latitude:  -21.64702,
      //   longitude: -45.84903
      // },
      // {
      //   id: 4,
      //   name: 'Açai da barra',
      //   tipo: 'Sorveteria',
      //   rating: 5,
      //   distance: '5km de distância',
      //   checkins: 5,
      //   favorite: false,
      //   Rua: 'R. Paulo do Vale, 301',
      //   Bairro: 'Centro',
      //   Municipio: 'Embu das Artes',
      //   Estado: 'São Paulo',
      //   CEP: '06804-060',
      //   latitude:  -28.64702,
      //   longitude: -44.84903
        
      // },
      // {
      //   id: 5,
      //   name: 'Lorem Ipsum 5',
      //   rating: 5,
      //   distance: '5km de distância',
      //   checkins: 5,
      //   favorite: false,
      //   Rua: 'Estr. Prof. Cândido Mota Filho, 195',
      //   Bairro: ' Jardim Recanto da Fonte',
      //   Municipio: 'Embu das Artes',
      //   Estado: 'São Paulo',
      //   CEP: '06804-445',
      //   latitude:  -26.64702,
      //   longitude: -47.84903
      // },
    ],
  };
  