export default {
    commerceList: [
      {
        id: 1,
        tipo: 'Restaurante',
        name: 'Lorem Ipsum 1 Lorem Ipsum 1 Lorem',
        rating: 4,
        distance: '3km de distância',
        checkins: 2,
        favorite: true,
        Rua: 'R. Central',
        Bairro: 'Jardim Sto Eduardo',
        Municipio: 'Embu das Artes',
        Estado: 'São Paulo',
        CEP: '06823-510',
      },
      {
        id: 2,
        name: 'Lorem Ipsum 2',
        rating: 5,
        distance: '5km de distância',
        checkins: 5,
        favorite: false,
      },
      {
        id: 3,
        name: 'Lorem Ipsum 3',
        rating: 1,
        distance: '5km de distância',
        checkins: 5,
        favorite: false,
      },
      {
        id: 4,
        name: 'Lorem Ipsum 4',
        rating: 5,
        distance: '5km de distância',
        checkins: 5,
        favorite: false,
      },
      {
        id: 5,
        name: 'Lorem Ipsum 5',
        rating: 5,
        distance: '5km de distância',
        checkins: 5,
        favorite: false,
      },
    ],
  };
  